"""
Generate SHA-256 manifest for CORE/1.2 files.
"""
import hashlib
import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
os.chdir(REPO_ROOT)

FILES = [
    # ─── Source files ─────────────────────────────────────────────
    "apps/integration-api/src/receiver/protocol-fixture.ts",
    "apps/integration-api/src/receiver/hmac-verify.ts",
    "apps/integration-api/src/receiver/scope-verify.ts",
    "apps/integration-api/src/receiver/connection-registry.ts",
    "apps/integration-api/src/receiver/dedupe.ts",
    "apps/integration-api/src/receiver/handler.ts",
    "apps/integration-api/src/receiver/ack.ts",
    "apps/integration-api/src/server.ts",
    # ─── Config ──────────────────────────────────────────────────
    "packages/config/src/types.ts",
    "packages/config/src/loader.ts",
    "packages/config/examples/env.synthetic.example.ts",
    # ─── Tests ──────────────────────────────────────────────────
    "apps/integration-api/tests/receiver.test.mjs",
    "apps/integration-api/tests/receiver.int.test.mjs",
    "apps/integration-api/tests/pg-receiver-harness.mjs",
    "apps/integration-api/tests/server.test.mjs",
    # ─── Configs / package.json / synthetic env ──────────────────
    "packages/config/tests/loader.test.mjs",
    "apps/integration-api/package.json",
    "apps/integration-api/.env.synthetic.example",
]

print("# CORE/1.2 SHA-256 manifest (rev 2) — generated by scripts/core-1.2-manifest.py")
print("# Rev 2: F1/F2/F3 + guard fix bundle; rev 1 file list + connection-registry.ts.")
print(f"# Repo HEAD: {'unknown (no git)' if not os.path.exists('.git') else 'git'}")
print()

lines = []
for f in FILES:
    p = Path(f)
    if not p.exists():
        print(f"MISSING: {f}", flush=True)
        continue
    h = hashlib.sha256(p.read_bytes()).hexdigest()
    size = p.stat().st_size
    print(f"{h}  {f}  ({size}B)")
    lines.append((h, f, size))

manifest_path = Path("docs/contracts/handoff-core-1.2.manifest.txt")
with manifest_path.open("w", encoding="utf-8", newline="\n") as fh:
    fh.write("# CORE/1.2 SHA-256 manifest\n")
    fh.write("# Generated by scripts/core-1.2-manifest.py\n")
    fh.write(f"# {len(lines)} files\n")
    fh.write("\n")
    for h, f, size in lines:
        fh.write(f"{h}  {f}  ({size}B)\n")

print(f"\nWrote {manifest_path}")
