#!/usr/bin/env python3
"""Generate SHA-256 manifest cho CORE/1.3 bundle.

Output: docs/contracts/handoff-core-1.3.manifest.txt

Manifest covers:
  - Source code: packages/integration-store/src/**/*.ts
  - Schema + migration: packages/integration-store/prisma/**
  - Tests: packages/integration-store/tests/**/*.mjs
  - Config: package.json, tsconfig.json, .env.synthetic.example, .gitignore, README.md

Hash algorithm: SHA-256 (hex lowercase).
Format: `<sha256>  <relative-path>` (POSIX-friendly, 2-space separator).
Self-reference excluded (this script not part of bundle).

Sorted by relative path để deterministic across runs.
"""
import hashlib
import pathlib
import sys

ROOT = pathlib.Path('.').resolve()
OUT = ROOT / 'docs' / 'contracts' / 'handoff-core-1.3.manifest.txt'

INCLUDES = [
    'packages/integration-store/package.json',
    'packages/integration-store/tsconfig.json',
    'packages/integration-store/README.md',
    'packages/integration-store/.env.synthetic.example',
    'packages/integration-store/.gitignore',
    'packages/integration-store/prisma/schema.prisma',
    'packages/integration-store/prisma/migrations/migration_lock.toml',
    'packages/integration-store/prisma/migrations/0001_init/migration.sql',
    'packages/integration-store/src/client.ts',
    'packages/integration-store/src/errors.ts',
    'packages/integration-store/src/adapters.ts',
    'packages/integration-store/src/types.ts',
    'packages/integration-store/src/index.ts',
    'packages/integration-store/src/repos/contact-link.ts',
    'packages/integration-store/src/repos/conversation-link.ts',
    'packages/integration-store/src/repos/event-receipt.ts',
    'packages/integration-store/tests/unit/adapters.test.mjs',
    'packages/integration-store/tests/integration/pg-test-harness.mjs',
    'packages/integration-store/tests/integration/contact-link.int.test.mjs',
    'packages/integration-store/tests/integration/event-receipt.int.test.mjs',
    'docs/contracts/handoff-core-1.3.md',
]

EXCLUDE_FROM_MANIFEST = {
    'docs/contracts/handoff-core-1.3.manifest.txt',  # self
}


def sha256_file(p: pathlib.Path) -> str:
    h = hashlib.sha256()
    with open(p, 'rb') as f:
        for chunk in iter(lambda: f.read(65536), b''):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    rows = []
    for rel in sorted(INCLUDES):
        p = ROOT / rel
        if not p.exists():
            print(f'MISSING: {rel}', file=sys.stderr)
            return 1
        digest = sha256_file(p)
        rows.append((digest, rel))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('# SHA-256 manifest — CORE/1.3 Integration Store\n')
        f.write('# Algorithm: SHA-256 (hex lowercase)\n')
        f.write(f'# Files: {len(rows)}\n')
        f.write('# Generated by: scripts/core-1.3-manifest.py (NOT included in manifest itself)\n')
        f.write('# Sorted: relative path (deterministic across runs)\n')
        f.write('# Format: <sha256>  <relative-path>\n')
        f.write('#\n')
        for digest, rel in rows:
            f.write(f'{digest}  {rel}\n')

    print(f'Wrote {OUT} ({len(rows)} entries)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
