/**
 * scripts/generate-manifest-1.12.mjs — Generate / Verify SHA-256 manifest
 * for CORE/1.12 bundle.
 *
 * Generates docs/contracts/handoff-core-1.12.manifest.txt.
 * Separate from CORE/1.9 and CORE/1.11 manifests to preserve their
 * audit-PASS baselines as immutable evidence.
 *
 * Modes (mutually exclusive):
 *   (default)            Generate manifest (writes to default OUT_PATH or
 *                        to --output <path> if specified, for tests).
 *   --verify             Verify manifest against files on disk. READ-ONLY.
 *   --check              Coverage check. READ-ONLY.
 *
 * The --output flag only applies to generate (for tests using a scratch
 * path). --verify and --check are ALWAYS READ-ONLY against the bundled
 * OUT_PATH (the audit-PASS artifact), regardless of --output.
 */

import { readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..', '..');
const OUT_PATH = join(REPO_ROOT, 'docs/contracts/handoff-core-1.12.manifest.txt');

// CORE/1.12 bundle files
const BUNDLE_FILES = [
  // ── NEW: dashboard source files
  'apps/context-panel/src/dashboard/types.ts',
  'apps/context-panel/src/dashboard/fixtures.ts',
  'apps/context-panel/src/dashboard/aggregator.ts',
  'apps/context-panel/src/dashboard/store.ts',
  'apps/context-panel/src/dashboard/service.ts',
  // ── NEW: UI component
  'apps/context-panel/src/ui/components/dashboard-panel.tsx',
  // ── NEW: tests
  'apps/context-panel/tests/dashboard-aggregator.test.mjs',
  'apps/context-panel/tests/dashboard-service.test.mjs',
  'apps/context-panel/tests/dashboard-api.test.mjs',
  'apps/context-panel/tests/dashboard-no-model-no-db.test.mjs',
  'apps/context-panel/tests/dashboard-browser-evidence.mjs',
  'apps/context-panel/tests/manifest-readonly-1.12.test.mjs',
  // ── Generator
  'apps/context-panel/scripts/generate-manifest-1.12.mjs',
  // ── SHARED: modified files (additive, NOT replacing)
  'apps/context-panel/src/server.ts',
  'apps/context-panel/src/ui/app.tsx',
  // ── DOCS (handoff-core-1.12.md is referenced by entry, but the manifest
  //    itself is generated, NOT in BUNDLE_FILES to avoid self-reference).
  'docs/contracts/handoff-core-1.12.md',
  // Status supplement (mirrors CORE/1.11 pattern)
  'docs/contracts/handoff-core-1.12.status.md',
];

function sha256(buf) {
  return createHash('sha256').update(buf).digest('hex');
}

function checkCoverage() {
  const seen = new Set();
  const missing = [];
  const duplicates = [];
  for (const relPath of BUNDLE_FILES) {
    if (seen.has(relPath)) duplicates.push(relPath);
    seen.add(relPath);
    const fullPath = join(REPO_ROOT, relPath);
    if (!existsSync(fullPath)) missing.push(relPath);
  }
  return { duplicates, missing };
}

function generate(outPath = OUT_PATH) {
  const seen = new Set();
  const missing = [];
  const entries = [];

  for (const relPath of BUNDLE_FILES) {
    if (seen.has(relPath)) {
      throw new Error(`Duplicate entry: ${relPath}`);
    }
    seen.add(relPath);

    const fullPath = join(REPO_ROOT, relPath);
    if (!existsSync(fullPath)) {
      missing.push(relPath);
      continue;
    }
    const buf = readFileSync(fullPath);
    const stat = statSync(fullPath);
    const hash = sha256(buf);
    entries.push({ relPath, hash, size: stat.size });
  }

  if (missing.length > 0) {
    console.error('Missing files (cannot generate manifest):');
    for (const m of missing) console.error('  - ' + m);
    process.exit(1);
  }

  const now = new Date().toISOString();
  let out = '';
  out += '# CORE/1.12 — Handoff Manifest\n';
  out += '# Date: ' + now + '\n';
  out += '# Generator: scripts/generate-manifest-1.12.mjs (SHA-256)\n';
  out += '# Total files: ' + entries.length + '\n';
  out += '#\n';
  out += '# CORE/1.12 delta from CORE/1.11 baseline:\n';
  out += '#  - NEW: 12 files (5 dashboard src + 1 UI + 5 tests + 1 manifest read-only)\n';
  out += '#  - SHARED: 2 files (server.ts, app.tsx) — extended with dashboard routes/tab\n';
  out += '#  - DOCS: 1 file (handoff-core-1.12.md, generated by manifest)\n';
  out += '#\n';
  out += '# SHARED files: their hashes reflect CURRENT (post-delta) state, NOT\n';
  out += '# the CORE/1.11 audit-PASS hash. To compare against CORE/1.11 baseline,\n';
  out += '# see docs/contracts/handoff-core-1.11.manifest.txt — the SHARED files\n';
  out += '# are listed in BOTH manifests with potentially different hashes.\n';
  out += '#\n';
  out += '# Format: FILE|<repo-relative-path>|<sha256-hex>\n';
  out += '#\n';
  out += '\n';
  for (const e of entries) {
    out += `FILE|${e.relPath}|${e.hash}\n`;
  }
  out += '\n# Verification (READ-ONLY):\n';
  out += '#   node scripts/generate-manifest-1.12.mjs --verify\n';
  out += '#   node scripts/generate-manifest-1.12.mjs --check\n';

  writeFileSync(outPath, out, 'utf-8');
  console.log(`Manifest written: ${relative(REPO_ROOT, outPath)} (${entries.length} entries).`);
}

function verify() {
  if (!existsSync(OUT_PATH)) {
    console.error(`verify FAIL: manifest not found at ${OUT_PATH}`);
    process.exit(1);
  }
  const raw = readFileSync(OUT_PATH, 'utf-8');
  const lines = raw.split('\n').filter((l) => l.startsWith('FILE|'));
  const manifestEntries = lines.map((l) => {
    const [, relPath, hash] = l.split('|');
    return { relPath, hash };
  });

  const problems = [];
  const checked = [];

  for (const { relPath, hash } of manifestEntries) {
    const fullPath = join(REPO_ROOT, relPath);
    if (!existsSync(fullPath)) {
      problems.push(`missing on disk: ${relPath}`);
      continue;
    }
    const actual = sha256(readFileSync(fullPath));
    if (actual !== hash) {
      problems.push(`hash mismatch: ${relPath} (manifest=${hash} actual=${actual})`);
    }
    checked.push(relPath);
  }

  // Cross-check: every BUNDLE_FILES entry must be present.
  const seen = new Set(manifestEntries.map((e) => e.relPath));
  for (const relPath of BUNDLE_FILES) {
    if (!seen.has(relPath)) problems.push(`bundle file not in manifest: ${relPath}`);
  }

  if (problems.length === 0) {
    console.log(`verify OK: ${checked.length} entries matched, 0 missing, 0 mismatch.`);
    process.exit(0);
  } else {
    console.error(`verify FAIL: ${problems.length} problem(s)`);
    for (const p of problems) console.error('  - ' + p);
    process.exit(1);
  }
}

function check() {
  const { duplicates, missing } = checkCoverage();
  const problems = [];
  if (duplicates.length > 0) problems.push(`duplicate bundle entries: ${duplicates.join(', ')}`);
  if (missing.length > 0) problems.push(`missing bundle files: ${missing.join(', ')}`);

  if (problems.length === 0) {
    console.log(`check OK: ${BUNDLE_FILES.length} bundle entries clean.`);
    process.exit(0);
  } else {
    console.error(`check FAIL:`);
    for (const p of problems) console.error('  - ' + p);
    process.exit(1);
  }
}

const argv = process.argv.slice(2);
if (argv.includes('--verify')) {
  verify();
} else if (argv.includes('--check')) {
  check();
} else {
  // Optional --output <path> lets tests generate to a scratch location
  // without overwriting the bundled audit-PASS manifest at OUT_PATH.
  // Default behavior (no flag) preserves the previous behavior of writing
  // to the canonical OUT_PATH.
  let outPath = OUT_PATH;
  const outIdx = argv.indexOf('--output');
  if (outIdx !== -1 && outIdx + 1 < argv.length) {
    outPath = join(REPO_ROOT, argv[outIdx + 1]);
  }
  generate(outPath);
}
